"""update table schema

Revision ID: 5419c77ad02f
Revises: 34cb7a687fcc
Create Date: 2026-08-01 20:45:07.962975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5419c77ad02f'
down_revision: Union[str, Sequence[str], None] = '34cb7a687fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'auth_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
